name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - 'ludashi-plus/4.0'

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install required SDK components
        run: |
          sdkmanager "platform-tools" \
                     "platforms;android-26" \
                     "build-tools;35.0.0" \
                     "cmake;3.22.1" \
                     "ndk;29.0.14206865"

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Initialize submodules
        run: git submodule update --init --recursive

      - name: Build APK
        run: ./gradlew assembleDebug --no-daemon

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Winlator-Ludashi-Plus-4.0-debug
          path: |
            app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
